language: cpp
os: linux
dist: trusty
  
compiler:
  - g++
  - clang

addons:
  apt:
    update: true
    packages:
      - lcov

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++17
  - g++ --version
  - sudo apt-get install -qq g++-9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  - g++ --version

script:
  - g++ --version
  - lcov --version
  - gcov --version
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./LogicalImages-ut

after_success:
    # Create report
    - cd ${TRAVIS_BUILD_DIR}
    - lcov --directory . --capture --output-file coverage.info
    - lcov --remove coverage.info '/user/*' --output-file coverage.info
    - lcov --list coverage.info
    # Upload report to CodeCov
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-9 || echo "Codecov did not collect coverage reports"

